
# SEO settings
title: "Binary"
title2: "Reality" # default: ""
description: "Under Naked Eyes"
keywords: "Software, Engineering, Computer, Science, Programming, Blockchain, hijacking, Haskell"
url: https://phuoc-thanh.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/phuoc-thanh/phuoc-thanh.github.io
# disqus_shortname: "binaryreality"
# twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Phuoc-Thanh Do"
  job      : "citizen of the Matrix"
  bio      : "It's a funny thing about comin' home. Looks the same, smells the same, feels the same. You'll realize what's changed is you."
  thumb    : /images/author.jpg
  email    : thanhdo89se@gmail.com
  url      : http://phuoc-thanh.github.io
  github   : http://github.com/phuoc-thanh
  facebook : https://www.facebook.com/naiveryan

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-seo-tag

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
